# Generated by Django 3.2 on 2021-04-14 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distance',
            old_name='location',
            new_name='origin',
        ),
    ]
